### ISSUE TITLE
Tracking: new packages required for voctomix2

### ISSUE THREAD

**Issue by danimo** [voc/cm#10]
New packages required for encoder role:

- [ ] python3-scipy

New packages required for mixer role:

- [ ] fonts-roboto

**Comment by fightling** [comment]
Also you'll need to replace these two files to get the right view on the c3voc-UHD laptops:

[voctomix-files.zip](https://github.com/voc/cm/files/2672490/voctomix-files.zip)

/opt/voctomix/release/voctogui/ui/voctogui.css

**Comment by danimo** [comment]
They will simply be in the branch, right?

**Comment by fightling** [comment]
> They will simply be in the branch, right?

I can add the css to the branch but the config is outside the repo (in the folder above) on the laptops.

**Comment by fightling** [comment]
FYI: I've committed the CSS-file including large fonts into the branch.

**Comment by fightling** [comment]
Please update the voctogui-config.ini file:

[voctogui-config.ini.zip](https://github.com/voc/cm/files/2674400/voctogui-config.ini.zip)
