### ISSUE TITLE
Make streaming website https only

### ISSUE THREAD

**Issue by danimo** [voc/cm#17]
Putting this here since it's *mostly* nginx rules that need rework.

**Goal:** HTTPS everywhere for streaming.media.ccc.de
**When:** We have been delaying this forever, let's just get over with it ASAP
**How:** Multistep approach.

Challenge: we have an API that does not mandate the use of HTTPS. So we must assume that some clients/software using that API is not HTTPS-proof.

2. Introduce HTTP 302 redirect for every page that will be served to a web browser
2.1. Remove HTTP(S) toggle button (streaming-website repo)
3. Do not force a redirect for the API routes
4. Do not force a redirect for anything that is requested via HTTP,  except for browser-oriented pages
5. Deprecate HTTP access to the API, set and announce a sunset date
6. Monitor changes. If there are no major incidents, switch 302's to 301's
6. After announced time frame, sunset HTTP-only access for good
7. Monitor HTTP only traffic. Decide whether it's worth extending the sunset
8. If not, set HSTS header -> done.

**Comment by iSchluff** [comment]
We are done with that, right?

**Comment by danimo** [comment]
Yes
