### ISSUE TITLE
Remove yadif from Streaming-Scripts and Voctogui

### ISSUE THREAD

**Issue by MaZderMind** [voc/cm#3]
Since we're now using voctomix' internal decklink-sources, which already do implement a yadif deinterlacer in the source pipeline, we should remove the extra deinterlacer from
 - the streaming-scripts
 - the voctogui configuration

and in the long run also from our tracker encoding-profiles
// cc @Florob @a-tze

**Comment by a-tze** [comment]
In the very past, we deinterlaced on capture/recording. There was a point in time 2 or 3 years ago when we intentionally stopped doing this. I have a strong opinion against deinterlacing the sources:
  * it can unpredictably blow up your CPU load (in addition this effort is wasted when having more than 2 sources)
  * the deinterlacer can be wrong and then you have no usable recording
  * there isnt only voctomix, so deinterlacing will always be present in tracker encoding profiles (it does detection, so it doesnt hurt on progressive content)

**Comment by MaZderMind** [comment]
@a-tze I accept your argument and added the `needs-discussion`-label to this issue. This is a reminder that there is currently an discrepancy in the voc-setup with the decklink sources doing the deinterlacing *as well as* the streaming and the recording scripts.

One of them must be changed.
See voc/voctomix#154 for a discussion on making the deinterlacer in the decklink sources configurable

**Comment by derpeter** [comment]
If we mix declink sources with other sources that are already interlaced like e.g. JVC-CAM RTMP, what would be / is the impact of mixing interlaced and deinterlaced content in voctomix?. In other words: I would vote for the solution that gives the maximum flexibility on inputs. Deinterlacing after the mixing sounds the most sane solution if there is no impact on possibility of sources.

**Comment by v0tti** [comment]
Is there any reason for staying at 1080i50 for the camera inputs anyway? For talk recordings 1080p25 or 720p50 should be good enough.

**Comment by a-tze** [comment]
Assuming you do not want to scale (so all inputs need to have the same resolution) then 720 has the disadvantage that you loose a lot of pixels on the slide capture. i50 vs. p25 is a matter of taste, i50 just looks smoother but the difference will not be that visible for talks, yes.

**Comment by saerdnaer** [comment]
> Is there any reason for staying at 1080i50 for the camera inputs anyway?

@v0tti We have to check if the JVC cams actually support an 1080p25 via SDI output. Our Panasonic cams have a special P25 mode for that ensuring the same input frame is used for both fields, c.f. https://c3voc.de/wiki/hardware:ag-ac-160-eej#progressive_mode.

**Comment by a-tze** [comment]
@MaZderMind we had a short discussion yesterday and iirc we want to evaluate switching to p25 (e.g. does all the hardware support it and does it work as expected).
