### ISSUE TITLE
Add smb default user

### ISSUE THREAD

**Issue by saerdnaer** [voc/cm#4]
`smbpasswd -a voc`

**Comment by a-tze** [comment]
I think MacOS can now handle guest acces, right? So this should be obsolete now.

**Comment by saerdnaer** [comment]
I'm not sure and have to test it, next time a have a voc storage instance in front of me.

**Comment by a-tze** [comment]
You can test this with any samba installation, there is nothing special in a voc storage.

**Comment by saerdnaer** [comment]
Confirmed: I delete the user credentials for user voc on my client running macOS 10.12.6 and still could connect to storage.lan.c3voc.de as guest. Writing shotcut project files also worked.
