### ISSUE TITLE
Switch to libopus encoder

### ISSUE THREAD

**Issue by anotherwon** [voc/cm#9]
https://github.com/voc/cm/blob/07a3942e847066f0f0ddb84a845fa8b416573346/ansible/roles/audio-pi/templates/audio-ingest.sh.j2#L6

ffmpeg's native opus encoder is still considered experimental.
Since you're not using `-strict experimental` this script should always fail.
I suggest using `-c:a libopus` instead.

**Comment by dedeibel** [comment]
Have you tested it using the whole setup routine? It worked for us.

Nonetheless we can adopt the changes after testing, there is no preference. Will try to test it some time after the next week.

**Comment by anotherwon** [comment]
ffmpeg allows either a codec or a specific encoder or decoder implementation of a codec in the _-codec_ option.
If the parameter is not the name of an implementation it will automatically select the first suitable one.

The reason it currently works is that you're using ffmpeg 3.2.
The native (experimental) opus encoder was introduced in 3.3 (https://github.com/FFmpeg/FFmpeg/blob/master/Changelog#L201).
Therefore libopus is the only encoder available for the codec opus and automatically selected.
See: `ffmpeg -codecs | grep Opus`

This will break with the next release as the native encoder will be the first option then.
I haven't tested it because I don't have the hardware available. ;)

**Comment by derchrisuk** [comment]
We are using ffmpeg 3.4

**Comment by anotherwon** [comment]
Huh, well color me surprised. I thought this was a standard Raspbian image which, I checked, is still on 3.2.
I see that Ubuntu 18.04LTS is on 3.4 though.
Are you perhaps looking at a regular machine instead of a Raspberry Pi?

**Comment by dedeibel** [comment]
Thank your very much for the contribution. I tested it and it works. (Previous version still worked too but as you said, might fail in the future). Sorry it took a while.
